print("Day 1-String Manipulation")
print("String Concatenation is done with the"+"sign.")
print('e.g.print("hello"+"would")')
print("New lines can be created with a backslash and n.")
print("Day 1-String Manipulation")
print("String Concatenation is done with the"+"sign.")
print('e.g.print("hello"+"would")')
print("New lines can be created with a backslash and n.")
print("Day 1-String Manipulation")
print("String Concatenation is done with the"+"sign.")
print('e.g.print("hello"+"would")')
print("New lines can be created with a backslash and n.")
print("Day 1-String Manipulation")
print("String Concatenation is done with the"+"sign.")
print('e.g.print("hello"+"would")')
print("New lines can be created with a backslash and n.")
print("Day 1-String Manipulation")
print("String Concatenation is done with the"+"sign.")
print('e.g.print("hello"+"would")')
print("New lines can be created with a backslash and n.")
